### ISSUE TITLE
LN1-Compressed Sparse Row (CSR) 

### ISSUE THREAD

**Issue by orlandocosta76** [LDSSA/batch2-blu11#2]
Hi, the example given for CSR is not correct regarding the indptr:
` [0, 2, 2, 4]`
the last value should be 3,  as this vector should have _m +1_ length, where _m_ is the number of rows, and the last position holds the total number of non-zero values.

**Comment by hugorcf** [comment]
I sincerely spent ages trying to understand that part of the LN. It would have been much easier to just put the recursive mathematical definition to the indptr, as in https://en.m.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_(CSR_or_CRS).
