### ISSUE TITLE
Ex 2.4 Best-item Content-based 

### ISSUE THREAD

**Issue by orlandocosta76** [LDSSA/batch2-blu11#4]
Hi,  it seems that the grader has an inconsistent behaviour regarding this question since it gives me full credit (20) either if I leave the last line as:
- `raise NotImplementedError()` 
- or `return <indexes for the maximum value per row>` (with the latter failing the asserts)

Regarding the asserts, can you check that the hash values are the correct ones?

**Comment by migvieira** [comment]
Hi Orlando,

I had the same issue, assert fails, but when submiiting apparently I got it right.

for me the hash for the  hashlib.sha256(L[665][0, 0]).hexdigest() is 
'dd89907308f047004b8d7a2c93bbbcebe1d8502c0160e7ee259fabab00aaec6f'
do you get the same hash?

**Comment by orlandocosta76** [comment]
@migvieira Yes, I got the same hash value as well :)
