### ISSUE TITLE
LN2 Section 3.1 TF-IDF Weighting

### ISSUE THREAD

**Issue by orlandocosta76** [LDSSA/batch2-blu11#5]
In this section we define that we want to compute the TF-IDF (Term's Frequency - Inverse Document Frequency). But later, on section 3.4.4 Building a Wrapper, we have the code:
 `idf = np.log(np.divide(nrows,  genre_count)) `

So, it seems we are using only the IDF, not TF-IDF (which would require some multiplication), or am I missing something?

**Comment by hugorcf** [comment]
I also think that the _tf_(_i_, _t_) is missing. As it's said in section 3.4.3, the frequency count is either 0 or 1, so for any given movie _i_ without a given genre _t_, _tf_(_i_, _t_) = 0, which means that the _tfidf_(_i_,_t_, _I_) = 0.
