### ISSUE TITLE
Exercises notebook, 1.3 - help with assert

### ISSUE THREAD

**Issue by pma2** [LDSSA/batch2-blu11#6]
I'm having problem with exercise 1.3, on the first block:
"We start by building two helper functions, to finding out the row and column indices for each rating."

I built the two functions. They pass the shape asserts but fail the content asserts:
```
expected_hash = 'ae86f791757dce0e3800c3803b560df4d3825c2cbf254ef5b9f8ea3bdea8fdcc'
assert(hashlib.sha256(rows[4457]).hexdigest() == expected_hash)

expected_hash = 'f5c50ec3895168b69eb366805086712f30164e9ff0b0e8a26e109140efc2da6f'
assert(hashlib.sha256(cols[4457]).hexdigest() == expected_hash)
```
Any useful information? 
Thanks

**Comment by pma2** [comment]
After many headaches is resolved forcing type of the output -> numpy.int64...
Although the result was the same, the different data type resulted in different hash result!
Thanks Sofia :)

**Comment by orlandocosta76** [comment]
@pma2 I was going to suggest that, but it happened in 1.1 assert, so even before 1.3 :)

**Comment by ddbortoli** [comment]
I'm having the same problem starting from question 1.1, even when changing the output type to `numpy.int64`. Any suggestions?
Did you have to define the file encoding the opening it?

**Comment by ddbortoli** [comment]
What solved it to me was using `dtype=np.dtype(object)` (or `dtype='object'`) when opening the files.

**Comment by HugoDLopes** [comment]
This is actually a problem. You should have had something like:
```
def make_ratings_rows(users, users_from_ratings):
    # Combine a list comprehension with np.argwhere to find the index for each 
    # row in `users_from_ratings` in `users`.
    # Remember, to extract the first element of the resulting array use [0, 0].
    # Hint: explore the docs of the function np.argwhere and try it out.
    # rows = ...
    ### BEGING SOLUTION
    
    ### END SOLUTION
    return np.array(rows)


def make_ratings_cols(items, items_from_ratings):
    # Combine a list comprehension with np.argwhere to find the index for each 
    # column in `items_from_ratings` in `items`.
    # Remember, to extract the first element of the resulting array use [0, 0].
    # Hint: explore the docs of the function np.argwhere and try it out.
    # cols = ...
    ### BEGING SOLUTION
    
    ### END SOLUTION
    return np.array(cols)
```
